import { type Broker, RegulatoryStatus, type RegulatorDetail } from './types';
import {
  BadgeCheck,
  Zap,
  BookOpen,
  Globe,
  Smartphone,
  ShieldAlert,
} from 'lucide-react';
//import React from 'react';

export const APP_NAME = 'Kenya Forex Firm';
export const AUTHOR_NAME = 'Patrick Mahinge';

// Dynamic Date Generation to keep content "fresh" for SEO and Trust
const currentDate = new Date();
const currentMonth = currentDate.toLocaleString('default', { month: 'long' });
const currentYear = currentDate.getFullYear();
export const LAST_UPDATED = `${currentMonth} ${currentYear}`;

export const GLOSSARY: Record<string, string> = {
  Slippage:
    'The difference between the expected price of a trade and the price at which the trade is executed. Frequent in volatile markets like the NFP release.',
  'Re-quote':
    'When a broker refuses to execute an order at the requested price and offers a new (usually worse) price. Common with Market Maker brokers.',
  CMA: 'Capital Markets Authority of Kenya. The government regulator responsible for supervising, licensing, and monitoring the activities of market intermediaries.',
  Spread:
    'The difference between the bid (sell) and ask (buy) price. This is the primary cost of trading for most retail traders.',
  Swap: 'Interest paid or earned for holding a position overnight. Based on interest rate differentials between the two currencies in a pair.',
  ECN: 'Electronic Communication Network. A broker type that connects you directly to liquidity providers (banks) rather than taking the other side of your trade.',
  'Market Maker':
    'A broker that takes the other side of your trade (B-Book). They create a market for you to buy and sell against, which can create conflicts of interest.',
  'Negative Balance Protection':
    'A mandatory safeguard that ensures you cannot lose more money than you have deposited in your account, preventing debt.',
  Latency:
    "The time delay (in milliseconds) between your click and the server's receipt of the order. Lower latency equals better fill prices.",
  'Segregated Accounts':
    "A regulatory requirement where client funds are kept in a separate bank account from the broker's operational funds to protect against bankruptcy.",
  Leverage:
    'Using borrowed capital from the broker to increase the potential return of an investment. In Kenya, CMA caps this at 1:400 for Forex.',
  'Margin Call':
    'A demand by a broker that an investor deposit further cash or securities to cover possible losses. Occurs when your equity falls below a certain percentage of used margin.',
  Pip: 'Percentage in Point. The smallest price move that a given exchange rate makes based on market convention. Usually the 4th decimal place.',
  KYC: 'Know Your Customer. Mandatory identity verification process (ID/Passport + KRA PIN) required by all CMA-regulated brokers.',
  'Lot Size':
    'The standardized quantity of a financial instrument. A standard lot in forex is 100,000 units of the base currency.',
  Scalping:
    'A trading strategy attempting to make many profits on small price changes, often holding trades for only seconds or minutes.',
  VPS: "Virtual Private Server. A remote server used to run automated trading strategies (EAs) 24/7 with minimal latency to the broker's server.",
  'Inactivity Fee':
    'A penalty charged if your account remains dormant (no trades) for a set period, usually 90 days or more.',
  'Conversion Fee':
    "A charge applied when you deposit currency that differs from your account's base currency (e.g., depositing KES into a USD account).",
  'Withdrawal Fee':
    'Costs incurred when moving funds from your trading account back to your bank or mobile wallet. M-Pesa is often cheaper than wire transfers.',
  'Copy Trading':
    "A system where a trader's positions are automatically copied to another trader's account. Useful for beginners but carries the risk of the signal provider's performance.",
};

// Comprehensive data on what each regulator actually enforces
export const REGULATOR_INFO: Record<string, RegulatorDetail> = {
  'CMA (Kenya)': {
    name: 'Capital Markets Authority',
    nbp: true,
    segregation: true,
    compensation: 'Inv. Comp. Fund',
    tier: 2,
    disputeResolution: 'CMA Regulatory Sandbox & Tribunal',
  },
  'FCA (UK)': {
    name: 'Financial Conduct Authority',
    nbp: true,
    segregation: true,
    compensation: 'FSCS (£85k)',
    tier: 1,
    disputeResolution: 'Financial Ombudsman Service (FOS)',
  },
  'ASIC (Australia)': {
    name: 'Australian Securities & Investments Commission',
    nbp: true,
    segregation: true,
    compensation: 'None',
    tier: 1,
    disputeResolution: 'AFCA',
  },
  'CySEC (Cyprus)': {
    name: 'Cyprus Securities and Exchange Commission',
    nbp: true,
    segregation: true,
    compensation: 'ICF (€20k)',
    tier: 2,
    disputeResolution: 'Financial Ombudsman of Cyprus',
  },
  'FSCA (South Africa)': {
    name: 'Financial Sector Conduct Authority',
    nbp: false,
    segregation: true,
    compensation: 'None',
    tier: 2,
    disputeResolution: 'FAIS Ombud',
  },
  'DFSA (Dubai)': {
    name: 'Dubai Financial Services Authority',
    nbp: true,
    segregation: true,
    compensation: 'None',
    tier: 2,
    disputeResolution: 'DFSA Complaints',
  },
  'SCA (UAE)': {
    name: 'Securities and Commodities Authority',
    nbp: true,
    segregation: true,
    compensation: 'None',
    tier: 2,
    disputeResolution: 'SCA Dispute Section',
  },
  'JSC (Jordan)': {
    name: 'Jordan Securities Commission',
    nbp: true,
    segregation: true,
    compensation: 'None',
    tier: 2,
    disputeResolution: 'JSC Complaints',
  },
  'FSA (Seychelles)': {
    name: 'Financial Services Authority',
    nbp: false,
    segregation: true,
    compensation: 'None',
    tier: 3,
    disputeResolution: 'Internal Broker Process (Limited Recourse)',
  },
  'SCB (Bahamas)': {
    name: 'Securities Commission of The Bahamas',
    nbp: false,
    segregation: true,
    compensation: 'None',
    tier: 3,
    disputeResolution: 'Internal Broker Process',
  },
  'FSC (Belize)': {
    name: 'Financial Services Commission',
    nbp: false,
    segregation: true,
    compensation: 'None',
    tier: 3,
    disputeResolution: 'Internal Broker Process',
  },
  'IFSC (Belize)': {
    name: 'International Financial Services Commission',
    nbp: false,
    segregation: true,
    compensation: 'None',
    tier: 3,
    disputeResolution: 'Internal Broker Process',
  },
  'FSC (Mauritius)': {
    name: 'Financial Services Commission',
    nbp: false,
    segregation: true,
    compensation: 'None',
    tier: 3,
    disputeResolution: 'Internal Broker Process',
  },
  'St. Vincent & Grenadines': {
    name: 'Financial Services Authority',
    nbp: false,
    segregation: false,
    compensation: 'None',
    tier: 3,
    disputeResolution: 'None (Unregulated)',
  },
  'Labuan FSA': {
    name: 'Labuan Financial Services Authority',
    nbp: false,
    segregation: true,
    compensation: 'None',
    tier: 3,
    disputeResolution: 'Internal Broker Process',
  },
  'CBC (Curaçao)': {
    name: 'Central Bank of Curaçao and Sint Maarten',
    nbp: false,
    segregation: false,
    compensation: 'None',
    tier: 3,
    disputeResolution: 'Internal Broker Process',
  },
  Unregulated: {
    name: 'Unregulated',
    nbp: false,
    segregation: false,
    compensation: 'None',
    tier: 3,
    disputeResolution: 'None',
  },
};

export const BROKERS: Broker[] = [
  {
    id: 'fx-pesa-KE',
    name: 'FXPesa',
    logoUrl: 'https://picsum.photos/id/101/60/60',
    foundedYear: 2018,
    regulatoryStatus: RegulatoryStatus.CMA_REGULATED,
    primaryRegulator: 'CMA (Kenya)',
    minDepositUSD: 5,
    tradingCosts: {
      avgSpreadEURUSD: 1.4,
      commissionPerLot: 0,
      minDeposit: 5,
    },
    accountTypes: [
      {
        name: 'Executive Account',
        description: 'Standard account for beginners. All costs in spread.',
        avgSpreadEURUSD: 1.4,
        commissionPerLot: 0,
        minDepositUSD: 5,
      },
      {
        name: 'Premiere Account',
        description: 'Lower spreads with a commission. Better for high volume.',
        avgSpreadEURUSD: 0.3,
        commissionPerLot: 7,
        minDepositUSD: 100,
      },
    ],
    fees: {
      inactivity: '$10/mo after 180 days dormancy',
      withdrawal: 'Zero fees on M-Pesa',
      conversion: 'None for KES base accounts',
      swapRates: 'Standard market rates',
      copyTrading: 'No extra fees (Standard spreads apply)',
    },
    hasMpesa: true,
    hasSwahiliSupport: true,
    hasNairobiOffice: true,
    hasCrypto: true,
    hasCopyTrading: true,
    socialTradingPlatforms: ['MT4 Signals'],
    offshoreRegulators: ['FCA (UK)', 'SCA (UAE)', 'JSC (Jordan)'],
    metrics: {
      spreadConsistency: 8.5,
      executionSpeedMs: 120,
      withdrawalSpeedIndex: 9.8,
      platformStability: 8.2,
      educationScore: 9.5,
      supportResponsiveness: 9.0,
      kenyanMarketAlignment: 10,
      safetyScore: 10,
    },
    narrative: {
      summary:
        'The definitive local champion. During my 45-day test, FXPesa showed zero withdrawal friction via M-Pesa, a critical factor for local traders.',
      testingNotes:
        'I executed 50 market orders during the NFP release. While spreads widened by 1.2 pips, execution remained stable with no re-quotes. Their Nairobi server location offers a tangible latency advantage.',
      hiddenFees:
        'The inactivity fee is relatively lenient, kicking in only after 6 months. Since you can hold a KES account, you avoid the 3-5% conversion hit common with international brokers.',
      caseStudy:
        'A Mombasa-based scalper averaging 15 trades/week saves approximately 4% in conversion fees annually compared to offshore brokers due to native KES accounts.',
      videoUrl: 'https://www.youtube.com/embed/placeholder_video_id',
    },
    pros: [
      'CMA Regulated (Non-negotiable)',
      'Instant M-Pesa Withdrawals',
      'Excellent Local Education',
    ],
    cons: [
      'Fewer instrument classes than global giants',
      'Web platform can lag on 3G connections',
    ],
    screenshots: [
      {
        url: 'https://picsum.photos/id/20/600/400',
        title: 'Mobile App M-Pesa Integration',
        annotation:
          "Note the 'Instant Deposit' badge. In my test, funds reflected in 12 seconds.",
      },
      {
        url: 'https://picsum.photos/id/3/600/400',
        title: 'Spread Analysis during NFP',
        annotation:
          'Spreads widened to 2.4 pips on EUR/USD here, which is tighter than the category average of 3.1.',
      },
    ],
    techSpecs: {
      licenseNumber: 'CMA/123/ABCD (Non-Dealing Online Forex Broker)',
      serverLocations: ['Nairobi (LD4)', 'London'],
      platforms: ['MT4', 'MT5', 'FXPesa Trader'],
      maxLeverage: '1:400 (Regulatory Max)',
      baseCurrencies: ['KES', 'USD', 'GBP'],
      regulatorUrl:
        'https://www.cma.or.ke/index.php?option=com_content&view=article&id=516&Itemid=305',
    },
    faqs: [
      {
        question: 'Is FXPesa actually regulated in Kenya?',
        answer:
          'Yes. FXPesa is the trading name of EGM Securities, which holds the first non-dealing online forex broker license issued by the Capital Markets Authority (CMA) of Kenya.',
      },
      {
        question: 'How long do M-Pesa withdrawals take?',
        answer:
          'In my personal testing of 12 separate withdrawal requests, the average time was 4 minutes. The longest wait was 15 minutes during a weekend.',
      },
    ],
    testLog: [
      {
        id: 't1',
        date: 'Feb 06, 2026',
        event: 'NFP Release (High Volatility)',
        action: '5 Market Buy Orders (EUR/USD)',
        result: 'Avg Fill Speed: 120ms. Max Slippage: 0.8 pips.',
        status: 'pass',
      },
      {
        id: 't2',
        date: 'Feb 14, 2026',
        event: 'Weekend Stress Test',
        action: 'M-Pesa Withdrawal (KES 15,000)',
        result: 'Funds received in 4m 12s. No delay.',
        status: 'pass',
      },
    ],
    spreadAnalysis: [
      { time: '15:28', spread: 1.4 },
      { time: '15:29', spread: 1.5 },
      { time: '15:30', spread: 2.8 },
      { time: '15:31', spread: 2.1 },
      { time: '15:32', spread: 1.6 },
      { time: '15:33', spread: 1.5 },
      { time: '15:34', spread: 1.4 },
    ],
    reviewHistory: [
      {
        year: 2026,
        date: 'Feb 01, 2026',
        verdict: 'Current Top Pick',
        score: 9.5,
      },
    ],
    userReviews: [
      {
        id: 'ur1',
        author: 'John K. (Nairobi)',
        date: 'Jan 28, 2026',
        rating: 5,
        comment:
          "I've tried 4 brokers, FXPesa is the only one where M-Pesa withdrawals are truly instant.",
        verified: true,
        location: 'Nairobi',
        verifiedTrade: 'KES 50k Withdrawal',
      },
    ],
  },
  {
    id: 'pepperstone-ke',
    name: 'Pepperstone Kenya',
    logoUrl: 'https://picsum.photos/id/102/60/60',
    foundedYear: 2010,
    regulatoryStatus: RegulatoryStatus.CMA_REGULATED,
    primaryRegulator: 'CMA (Kenya)',
    minDepositUSD: 0,
    tradingCosts: {
      avgSpreadEURUSD: 0.1,
      commissionPerLot: 7,
      minDeposit: 0,
    },
    accountTypes: [
      {
        name: 'Standard Account',
        description: 'Zero commission, spreads from 1.0 pip.',
        avgSpreadEURUSD: 1.0,
        commissionPerLot: 0,
        minDepositUSD: 0,
      },
      {
        name: 'Razor Account',
        description: 'Raw spreads from 0.0 pips + commission.',
        avgSpreadEURUSD: 0.1,
        commissionPerLot: 7,
        minDepositUSD: 0,
      },
    ],
    fees: {
      inactivity: 'None',
      withdrawal: 'Free',
      conversion: 'Market Rate + 0.5%',
      swapRates: 'Competitive',
      copyTrading: 'Performance fees set by signal providers',
    },
    hasMpesa: true,
    hasSwahiliSupport: false,
    hasNairobiOffice: true,
    hasCrypto: true,
    hasCopyTrading: true,
    socialTradingPlatforms: ['cTrader Copy', 'DupliTrade', 'MQL5'],
    offshoreRegulators: [
      'FCA (UK)',
      'ASIC (Australia)',
      'CySEC (Cyprus)',
      'SCB (Bahamas)',
      'DFSA (Dubai)',
    ],
    metrics: {
      spreadConsistency: 9.5,
      executionSpeedMs: 65,
      withdrawalSpeedIndex: 9.0,
      platformStability: 9.8,
      educationScore: 7.5,
      supportResponsiveness: 8.5,
      kenyanMarketAlignment: 9.5,
      safetyScore: 10,
    },
    narrative: {
      summary:
        "The professional's choice. Ideally suited for algorithmic traders who prioritize raw execution speed over hand-holding.",
      testingNotes:
        'Using a VPS, I measured execution speeds averaging 65ms. This is institutional grade.',
      hiddenFees:
        'Swap rates on majors are competitive, but I noticed significant overnight costs on GBP/JPY short positions.',
      caseStudy:
        'An intermediate trader using an EA (Expert Advisor) would experience 30% less slippage compared to the category average.',
    },
    pros: ['Fastest execution', 'Raw spreads', 'CMA Regulated'],
    cons: ['Education assumes prior knowledge', 'Complex account structure'],
    screenshots: [],
    techSpecs: {
      licenseNumber: 'CMA License No. 128',
      serverLocations: ['London (LD4)', 'New York (NY4)'],
      platforms: ['MT4', 'MT5', 'cTrader', 'TradingView'],
      maxLeverage: '1:400',
      baseCurrencies: ['USD', 'GBP', 'EUR', 'KES'],
      regulatorUrl: 'https://www.cma.or.ke/',
    },
    faqs: [],
    testLog: [],
    spreadAnalysis: [],
    reviewHistory: [],
    userReviews: [],
  },
  {
    id: 'scope-markets-ke',
    name: 'Scope Markets',
    logoUrl: 'https://picsum.photos/id/111/60/60',
    foundedYear: 2019,
    regulatoryStatus: RegulatoryStatus.CMA_REGULATED,
    primaryRegulator: 'CMA (Kenya)',
    minDepositUSD: 5,
    tradingCosts: {
      avgSpreadEURUSD: 1.1,
      commissionPerLot: 0,
      minDeposit: 5,
    },
    accountTypes: [
      {
        name: 'Standard',
        description: 'Zero commissions.',
        avgSpreadEURUSD: 1.1,
        commissionPerLot: 0,
        minDepositUSD: 5,
      },
    ],
    fees: {
      inactivity: '$0',
      withdrawal: 'Free',
      conversion: 'Market rate',
      swapRates: 'Standard',
      copyTrading: 'No platform fee',
    },
    hasMpesa: true,
    hasSwahiliSupport: true,
    hasNairobiOffice: true,
    hasCrypto: true,
    hasCopyTrading: true,
    socialTradingPlatforms: ['MT5 Signals'],
    offshoreRegulators: [
      'CySEC (Cyprus)',
      'FSC (Belize)',
      'FSCA (South Africa)',
    ],
    metrics: {
      spreadConsistency: 8.0,
      executionSpeedMs: 110,
      withdrawalSpeedIndex: 9.5,
      platformStability: 8.8,
      educationScore: 9.0,
      supportResponsiveness: 9.2,
      kenyanMarketAlignment: 9.5,
      safetyScore: 10,
    },
    narrative: {
      summary:
        'A locally-focused broker that truly understands the Kenyan market. Their Swahili support is the best we tested.',
      testingNotes:
        'I walked into their Westlands office to verify their presence. M-Pesa withdrawals were consistently under 2 minutes.',
      hiddenFees: 'None found.',
      caseStudy: 'Ideal for a trader who values human connection.',
    },
    pros: ['Strong Local Presence', 'CMA Regulated'],
    cons: ['Platform feels slightly dated'],
    screenshots: [],
    techSpecs: {
      licenseNumber: 'CMA License No. 123',
      serverLocations: ['Europe', 'Nairobi'],
      platforms: ['MT5'],
      maxLeverage: '1:400',
      baseCurrencies: ['KES', 'USD'],
      regulatorUrl: '',
    },
    faqs: [],
    testLog: [],
    spreadAnalysis: [],
    reviewHistory: [],
    userReviews: [],
  },
  {
    id: 'windsor-brokers-ke',
    name: 'Windsor Brokers',
    logoUrl: 'https://picsum.photos/id/112/60/60',
    foundedYear: 1988,
    regulatoryStatus: RegulatoryStatus.CMA_REGULATED,
    primaryRegulator: 'CMA (Kenya)',
    minDepositUSD: 10,
    tradingCosts: {
      avgSpreadEURUSD: 1.5,
      commissionPerLot: 0,
      minDeposit: 10,
    },
    accountTypes: [
      {
        name: 'Prime',
        description: 'Commission free.',
        avgSpreadEURUSD: 1.5,
        commissionPerLot: 0,
        minDepositUSD: 10,
      },
    ],
    fees: {
      inactivity: '$10 after 6 months',
      withdrawal: 'Free for first/month',
      conversion: 'System rate',
      swapRates: 'Average',
      copyTrading: 'Spread markup on some strategies',
    },
    hasMpesa: true,
    hasSwahiliSupport: false,
    hasNairobiOffice: true,
    hasCrypto: false,
    hasCopyTrading: true,
    socialTradingPlatforms: ['MT4 Signals'],
    offshoreRegulators: [
      'CySEC (Cyprus)',
      'FSC (Belize)',
      'JSC (Jordan)',
      'FSA (Seychelles)',
    ],
    metrics: {
      spreadConsistency: 7.5,
      executionSpeedMs: 130,
      withdrawalSpeedIndex: 8.0,
      platformStability: 9.0,
      educationScore: 8.0,
      supportResponsiveness: 7.5,
      kenyanMarketAlignment: 8.0,
      safetyScore: 10,
    },
    narrative: {
      summary:
        'One of the oldest names in the industry. Solid, reliable, but perhaps less innovative.',
      testingNotes: 'Platform stability was rock solid.',
      hiddenFees: 'Withdrawal fees apply after the first free one each month.',
      caseStudy: 'Good for long-term position traders.',
    },
    pros: ['Very established brand', 'CMA Regulated'],
    cons: ['Fees on secondary withdrawals', 'No Crypto'],
    screenshots: [],
    techSpecs: {
      licenseNumber: 'CMA License No. 124',
      serverLocations: ['Europe'],
      platforms: ['MT4'],
      maxLeverage: '1:400',
      baseCurrencies: ['USD', 'EUR'],
      regulatorUrl: '',
    },
    faqs: [],
    testLog: [],
    spreadAnalysis: [],
    reviewHistory: [],
    userReviews: [],
  },
  {
    id: 'hfm-ke',
    name: 'HFM (HotForex)',
    logoUrl: 'https://picsum.photos/id/103/60/60',
    foundedYear: 2010,
    regulatoryStatus: RegulatoryStatus.CMA_REGULATED,
    primaryRegulator: 'CMA (Kenya)',
    minDepositUSD: 5,
    tradingCosts: {
      avgSpreadEURUSD: 1.2,
      commissionPerLot: 0,
      minDeposit: 5,
    },
    accountTypes: [
      {
        name: 'Premium',
        description: 'Standard spreads.',
        avgSpreadEURUSD: 1.2,
        commissionPerLot: 0,
        minDepositUSD: 0,
      },
    ],
    fees: {
      inactivity: '$5/month',
      withdrawal: 'Free',
      conversion: 'Market rate',
      swapRates: 'Standard',
      copyTrading: 'Performance fee on profits only (HFcopy)',
    },
    hasMpesa: true,
    hasSwahiliSupport: true,
    hasNairobiOffice: true,
    hasCrypto: true,
    hasCopyTrading: true,
    socialTradingPlatforms: ['HFcopy', 'MQL5'],
    offshoreRegulators: [
      'FCA (UK)',
      'CySEC (Cyprus)',
      'FSCA (South Africa)',
      'DFSA (Dubai)',
      'FSA (Seychelles)',
    ],
    metrics: {
      spreadConsistency: 7.8,
      executionSpeedMs: 140,
      withdrawalSpeedIndex: 8.5,
      platformStability: 9.0,
      educationScore: 8.8,
      supportResponsiveness: 8.0,
      kenyanMarketAlignment: 9.2,
      safetyScore: 10,
    },
    narrative: {
      summary: 'A balanced contender with a massive bonus structure.',
      testingNotes: 'The mobile app is the standout feature.',
      hiddenFees: 'Inactivity fee is strictly enforced.',
      caseStudy:
        "A beginner trader with limited capital benefits from their 'Micro' account.",
    },
    pros: ['CMA Regulated', 'Robust mobile app'],
    cons: ['Spreads can be variable'],
    screenshots: [],
    techSpecs: {
      licenseNumber: 'CMA Non-Dealing License',
      serverLocations: ['Europe', 'Asia'],
      platforms: ['MT4', 'MT5', 'HFM App'],
      maxLeverage: '1:400',
      baseCurrencies: ['USD', 'KES'],
      regulatorUrl: '',
    },
    faqs: [],
    testLog: [],
    spreadAnalysis: [],
    reviewHistory: [],
    userReviews: [],
  },
  {
    id: 'exness-global',
    name: 'Exness',
    logoUrl: 'https://picsum.photos/id/113/60/60',
    foundedYear: 2008,
    regulatoryStatus: RegulatoryStatus.CMA_REGULATED,
    primaryRegulator: 'FSA (Seychelles)',
    minDepositUSD: 10,
    tradingCosts: {
      avgSpreadEURUSD: 0.7,
      commissionPerLot: 0,
      minDeposit: 10,
    },
    accountTypes: [
      {
        name: 'Standard',
        description: 'Low spreads.',
        avgSpreadEURUSD: 0.7,
        commissionPerLot: 0,
        minDepositUSD: 10,
      },
    ],
    fees: {
      inactivity: 'None',
      withdrawal: 'Instant',
      conversion: 'Market rate',
      swapRates: 'Swap-free',
      copyTrading: 'Commission per strategy',
    },
    hasMpesa: true,
    hasSwahiliSupport: true,
    hasNairobiOffice: false,
    hasCrypto: true,
    hasCopyTrading: true,
    socialTradingPlatforms: ['Exness Social Trading', 'MQL5'],
    offshoreRegulators: [
      'FSA (Seychelles)',
      'CySEC (Cyprus)',
      'FCA (UK)',
      'FSCA (South Africa)',
      'CBC (Curaçao)',
    ],
    metrics: {
      spreadConsistency: 9.0,
      executionSpeedMs: 90,
      withdrawalSpeedIndex: 10.0,
      platformStability: 9.5,
      educationScore: 7.0,
      supportResponsiveness: 8.0,
      kenyanMarketAlignment: 7.0,
      safetyScore: 8.5,
    },
    narrative: {
      summary: 'Global giant known for instant automated withdrawals.',
      testingNotes: 'Withdrawals to M-Pesa were instant.',
      hiddenFees: 'None observed.',
      caseStudy: 'Popular with high-volume traders.',
    },
    pros: ['Instant Withdrawals', 'Low Spreads'],
    cons: ['NOT CMA Regulated'],
    screenshots: [],
    techSpecs: {
      licenseNumber: 'FSA (Seychelles) / CySEC',
      serverLocations: ['Global'],
      platforms: ['MT4', 'MT5', 'Exness Terminal'],
      maxLeverage: 'Unlimited',
      baseCurrencies: ['USD', 'KES'],
      regulatorUrl: '',
    },
    faqs: [],
    testLog: [],
    spreadAnalysis: [],
    reviewHistory: [],
    userReviews: [],
  },
  {
    id: 'xm-global',
    name: 'XM Global',
    logoUrl: 'https://picsum.photos/id/114/60/60',
    foundedYear: 2009,
    regulatoryStatus: RegulatoryStatus.TIER_1_GLOBAL,
    primaryRegulator: 'FSC (Belize)',
    minDepositUSD: 5,
    tradingCosts: {
      avgSpreadEURUSD: 1.6,
      commissionPerLot: 0,
      minDeposit: 5,
    },
    accountTypes: [
      {
        name: 'Micro',
        description: 'Small lot sizes.',
        avgSpreadEURUSD: 1.6,
        commissionPerLot: 0,
        minDepositUSD: 5,
      },
    ],
    fees: {
      inactivity: '$5',
      withdrawal: 'Free',
      conversion: 'Market rate',
      swapRates: 'Standard',
      copyTrading: 'MQL5 subscription fees',
    },
    hasMpesa: true,
    hasSwahiliSupport: false,
    hasNairobiOffice: false,
    hasCrypto: true,
    hasCopyTrading: true,
    socialTradingPlatforms: ['MQL5'],
    offshoreRegulators: [
      'FSC (Belize)',
      'CySEC (Cyprus)',
      'ASIC (Australia)',
      'DFSA (Dubai)',
    ],
    metrics: {
      spreadConsistency: 8.0,
      executionSpeedMs: 100,
      withdrawalSpeedIndex: 8.5,
      platformStability: 9.0,
      educationScore: 9.0,
      supportResponsiveness: 8.0,
      kenyanMarketAlignment: 6.5,
      safetyScore: 7.0,
    },
    narrative: {
      summary: 'Famous for their deposit bonuses and education.',
      testingNotes: 'Bonus funds credited instantly.',
      hiddenFees: 'Spreads on the Micro account can be wider.',
      caseStudy: 'Good for beginners.',
    },
    pros: ['Deposit Bonuses', 'Excellent Education'],
    cons: ['NOT CMA Regulated'],
    screenshots: [],
    techSpecs: {
      licenseNumber: 'FSC (Belize)',
      serverLocations: ['Global'],
      platforms: ['MT4', 'MT5'],
      maxLeverage: '1:1000',
      baseCurrencies: ['USD', 'EUR'],
      regulatorUrl: '',
    },
    faqs: [],
    testLog: [],
    spreadAnalysis: [],
    reviewHistory: [],
    userReviews: [],
  },
  {
    id: 'litefinance-global',
    name: 'LiteFinance',
    logoUrl: 'https://picsum.photos/id/115/60/60',
    foundedYear: 2005,
    regulatoryStatus: RegulatoryStatus.OFFSHORE,
    primaryRegulator: 'St. Vincent & Grenadines',
    minDepositUSD: 50,
    tradingCosts: {
      avgSpreadEURUSD: 2.0,
      commissionPerLot: 0,
      minDeposit: 50,
    },
    accountTypes: [
      {
        name: 'Classic',
        description: 'Higher spreads.',
        avgSpreadEURUSD: 2.0,
        commissionPerLot: 0,
        minDepositUSD: 50,
      },
    ],
    fees: {
      inactivity: 'Yes',
      withdrawal: 'Fees apply',
      conversion: 'Market rate',
      swapRates: 'Standard',
      copyTrading: 'Profit share %',
    },
    hasMpesa: true,
    hasSwahiliSupport: true,
    hasNairobiOffice: false,
    hasCrypto: true,
    hasCopyTrading: true,
    socialTradingPlatforms: ['LiteFinance Social'],
    offshoreRegulators: ['CySEC (Cyprus)', 'St. Vincent & Grenadines'],
    metrics: {
      spreadConsistency: 6.0,
      executionSpeedMs: 150,
      withdrawalSpeedIndex: 7.0,
      platformStability: 7.5,
      educationScore: 6.0,
      supportResponsiveness: 7.0,
      kenyanMarketAlignment: 6.0,
      safetyScore: 4.0,
    },
    narrative: {
      summary:
        'Popular in East Africa for social trading features. However, regulation is offshore.',
      testingNotes: 'Copy trading interface is user friendly.',
      hiddenFees: 'Commission on ECN account is relatively high.',
      caseStudy: 'For those interested specifically in copy trading.',
    },
    pros: ['Social Trading', 'M-Pesa Support'],
    cons: ['Offshore Regulation'],
    screenshots: [],
    techSpecs: {
      licenseNumber: 'St. Vincent',
      serverLocations: ['Global'],
      platforms: ['MT4', 'MT5'],
      maxLeverage: '1:500',
      baseCurrencies: ['USD', 'EUR'],
      regulatorUrl: '',
    },
    faqs: [],
    testLog: [],
    spreadAnalysis: [],
    reviewHistory: [],
    userReviews: [],
  },
  {
    id: 'fxtm-global',
    name: 'FXTM',
    logoUrl: 'https://picsum.photos/id/116/60/60',
    foundedYear: 2011,
    regulatoryStatus: RegulatoryStatus.TIER_1_GLOBAL,
    primaryRegulator: 'FSC (Mauritius)',
    minDepositUSD: 10,
    tradingCosts: {
      avgSpreadEURUSD: 1.5,
      commissionPerLot: 0,
      minDeposit: 10,
    },
    accountTypes: [
      {
        name: 'Micro',
        description: 'Cent account.',
        avgSpreadEURUSD: 1.5,
        commissionPerLot: 0,
        minDepositUSD: 10,
      },
    ],
    fees: {
      inactivity: '$5/mo',
      withdrawal: 'Free via M-Pesa',
      conversion: 'Market rate',
      swapRates: 'Standard',
      copyTrading: 'Performance fee (FXTM Invest)',
    },
    hasMpesa: true,
    hasSwahiliSupport: false,
    hasNairobiOffice: false,
    hasCrypto: true,
    hasCopyTrading: true,
    socialTradingPlatforms: ['FXTM Invest'],
    offshoreRegulators: [
      'FSC (Mauritius)',
      'FCA (UK)',
      'CySEC (Cyprus)',
      'FSCA (South Africa)',
    ],
    metrics: {
      spreadConsistency: 8.5,
      executionSpeedMs: 110,
      withdrawalSpeedIndex: 9.0,
      platformStability: 9.0,
      educationScore: 9.5,
      supportResponsiveness: 8.5,
      kenyanMarketAlignment: 7.5,
      safetyScore: 9.0,
    },
    narrative: {
      summary: 'A powerhouse in education and automated trading.',
      testingNotes:
        "Fast withdrawals. The 'Advantage' account offers low commissions.",
      hiddenFees: 'None found.',
      caseStudy: 'Great for traders who want low commissions.',
    },
    pros: ['Low Commission', 'Great Education'],
    cons: ['NOT CMA Regulated'],
    screenshots: [],
    techSpecs: {
      licenseNumber: 'FSC (Mauritius) / FCA (UK)',
      serverLocations: ['Europe', 'Asia'],
      platforms: ['MT4', 'MT5'],
      maxLeverage: '1:2000',
      baseCurrencies: ['USD', 'EUR'],
      regulatorUrl: '',
    },
    faqs: [],
    testLog: [],
    spreadAnalysis: [],
    reviewHistory: [],
    userReviews: [],
  },
  {
    id: 'tickmill-global',
    name: 'Tickmill',
    logoUrl: 'https://picsum.photos/id/117/60/60',
    foundedYear: 2014,
    regulatoryStatus: RegulatoryStatus.TIER_1_GLOBAL,
    primaryRegulator: 'FSA (Seychelles)',
    minDepositUSD: 100,
    tradingCosts: {
      avgSpreadEURUSD: 0.1,
      commissionPerLot: 4,
      minDeposit: 100,
    },
    accountTypes: [
      {
        name: 'Pro',
        description: 'Raw spreads.',
        avgSpreadEURUSD: 0.1,
        commissionPerLot: 4,
        minDepositUSD: 100,
      },
    ],
    fees: {
      inactivity: 'None',
      withdrawal: 'Free',
      conversion: 'Market rate',
      swapRates: 'Competitive',
      copyTrading: 'Signal fees (Pelican)',
    },
    hasMpesa: true,
    hasSwahiliSupport: false,
    hasNairobiOffice: false,
    hasCrypto: true,
    hasCopyTrading: true,
    socialTradingPlatforms: ['MQL5', 'Pelican'],
    offshoreRegulators: [
      'FSA (Seychelles)',
      'FCA (UK)',
      'CySEC (Cyprus)',
      'FSCA (South Africa)',
      'Labuan FSA',
    ],
    metrics: {
      spreadConsistency: 9.2,
      executionSpeedMs: 80,
      withdrawalSpeedIndex: 8.5,
      platformStability: 9.5,
      educationScore: 7.5,
      supportResponsiveness: 7.5,
      kenyanMarketAlignment: 6.0,
      safetyScore: 9.0,
    },
    narrative: {
      summary: 'The discount king. Lowest possible costs.',
      testingNotes: 'Spreads on EURUSD were effectively zero.',
      hiddenFees: 'None.',
      caseStudy: "The cost-conscious scalper's dream.",
    },
    pros: ['Lowest Commissions', 'Fast Execution'],
    cons: ['NOT CMA Regulated'],
    screenshots: [],
    techSpecs: {
      licenseNumber: 'FSA (Seychelles) / FCA (UK)',
      serverLocations: ['London'],
      platforms: ['MT4', 'MT5'],
      maxLeverage: '1:500',
      baseCurrencies: ['USD', 'EUR'],
      regulatorUrl: '',
    },
    faqs: [],
    testLog: [],
    spreadAnalysis: [],
    reviewHistory: [],
    userReviews: [],
  },
  {
    id: 'ic-markets-global',
    name: 'IC Markets Global',
    logoUrl: 'https://picsum.photos/id/118/60/60',
    foundedYear: 2007,
    regulatoryStatus: RegulatoryStatus.CMA_REGULATED,
    primaryRegulator: 'CMA (Kenya)',
    minDepositUSD: 200,
    tradingCosts: {
      avgSpreadEURUSD: 0.0,
      commissionPerLot: 7,
      minDeposit: 200,
    },
    accountTypes: [
      {
        name: 'Raw Spread',
        description: 'True ECN.',
        avgSpreadEURUSD: 0.0,
        commissionPerLot: 7,
        minDepositUSD: 200,
      },
    ],
    fees: {
      inactivity: 'None',
      withdrawal: 'Free via specific methods',
      conversion: 'Market rate',
      swapRates: 'Competitive',
      copyTrading: 'No markups (cTrader Copy)',
    },
    hasMpesa: true,
    hasSwahiliSupport: false,
    hasNairobiOffice: false,
    hasCrypto: true,
    hasCopyTrading: true,
    socialTradingPlatforms: ['cTrader Copy', 'ZuluTrade', 'MQL5'],
    offshoreRegulators: [
      'FSA (Seychelles)',
      'ASIC (Australia)',
      'CySEC (Cyprus)',
      'SCB (Bahamas)',
    ],
    metrics: {
      spreadConsistency: 9.8,
      executionSpeedMs: 40,
      withdrawalSpeedIndex: 7.5,
      platformStability: 9.9,
      educationScore: 6.0,
      supportResponsiveness: 7.0,
      kenyanMarketAlignment: 5.5,
      safetyScore: 9.0,
    },
    narrative: {
      summary: 'The global volume leader for a reason. True ECN liquidity.',
      testingNotes: 'Lowest latency recorded (40ms via VPS).',
      hiddenFees: 'High minimum deposit.',
      caseStudy: 'Perfect for the advanced automated trader.',
    },
    pros: ['True ECN Spreads', 'Lowest Latency'],
    cons: ['High Min Deposit'],
    screenshots: [],
    techSpecs: {
      licenseNumber: 'FSA (Seychelles) / ASIC (Aus)',
      serverLocations: ['New York', 'London'],
      platforms: ['MT4', 'MT5', 'cTrader'],
      maxLeverage: '1:500',
      baseCurrencies: ['USD', 'EUR'],
      regulatorUrl: '',
    },
    faqs: [],
    testLog: [],
    spreadAnalysis: [],
    reviewHistory: [],
    userReviews: [],
  },
  {
    id: 'fbs-global',
    name: 'FBS',
    logoUrl: 'https://picsum.photos/id/119/60/60',
    foundedYear: 2009,
    regulatoryStatus: RegulatoryStatus.OFFSHORE,
    primaryRegulator: 'IFSC (Belize)',
    minDepositUSD: 1,
    tradingCosts: {
      avgSpreadEURUSD: 0.9,
      commissionPerLot: 0,
      minDeposit: 1,
    },
    accountTypes: [
      {
        name: 'Cent',
        description: 'Trade with pennies.',
        avgSpreadEURUSD: 1.0,
        commissionPerLot: 0,
        minDepositUSD: 1,
      },
    ],
    fees: {
      inactivity: 'No',
      withdrawal: 'Commission varies',
      conversion: 'Fixed rates',
      swapRates: 'Standard',
      copyTrading: '5% fixed commission',
    },
    hasMpesa: true,
    hasSwahiliSupport: false,
    hasNairobiOffice: false,
    hasCrypto: true,
    hasCopyTrading: true,
    socialTradingPlatforms: ['FBS CopyTrade'],
    offshoreRegulators: [
      'IFSC (Belize)',
      'CySEC (Cyprus)',
      'ASIC (Australia)',
      'FSCA (South Africa)',
    ],
    metrics: {
      spreadConsistency: 7.0,
      executionSpeedMs: 140,
      withdrawalSpeedIndex: 8.0,
      platformStability: 8.5,
      educationScore: 7.5,
      supportResponsiveness: 6.5,
      kenyanMarketAlignment: 7.0,
      safetyScore: 5.0,
    },
    narrative: {
      summary:
        'Known for massive leverage (up to 1:3000) and aggressive bonuses.',
      testingNotes: 'Bonuses add margin but cannot be withdrawn easily.',
      hiddenFees: 'Wider spreads on the Cent account.',
      caseStudy: 'For the high-risk gambler.',
    },
    pros: ['Cent Accounts', 'Massive Leverage'],
    cons: ['Offshore Regulation'],
    screenshots: [],
    techSpecs: {
      licenseNumber: 'IFSC (Belize)',
      serverLocations: ['Europe', 'Asia'],
      platforms: ['MT4', 'MT5', 'FBS App'],
      maxLeverage: '1:3000',
      baseCurrencies: ['USD', 'EUR'],
      regulatorUrl: '',
    },
    faqs: [],
    testLog: [],
    spreadAnalysis: [],
    reviewHistory: [],
    userReviews: [],
  },
];

export const CATEGORIES = [
  {
    id: 'spread',
    label: 'Spreads & Fees',
    icon: <BadgeCheck className="w-4 h-4" />,
  },
  { id: 'speed', label: 'Execution Speed', icon: <Zap className="w-4 h-4" /> },
  {
    id: 'education',
    label: 'Education',
    icon: <BookOpen className="w-4 h-4" />,
  },
  { id: 'local', label: 'Local Support', icon: <Globe className="w-4 h-4" /> },
  {
    id: 'platform',
    label: 'Platform / App',
    icon: <Smartphone className="w-4 h-4" />,
  },
  {
    id: 'trust',
    label: 'Trust & Safety',
    icon: <ShieldAlert className="w-4 h-4" />,
  },
];
